### ISSUE TITLE
Application icon is corrupted

### ISSUE THREAD

**Issue by equin0x80** [charlierobson/EightyOne#39]
Years ago I drew the application icon for EightyOne (Source/icons/zx81.ico).
But at some point it got corrupted in your project: the white and transparent areas got mixed up, I think, so the keyboard looks wrong, with white keys missing. Here is the original, correct icon again.

[zx81.zip](https://github.com/charlierobson/EightyOne/files/5876153/zx81.zip)

**Comment by ZXFruitcake** [comment]
Thanks. The icon will be included in the next version of the emulator released.
